CREATE TABLE T_BLOG (
  BLOG_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_ID INTEGER UNSIGNED NOT NULL,
  BLOG_TITLE VARCHAR(50) NOT NULL,
  BLOG_CONTENT VARCHAR(5000) NULL,
  BLOG_DATE DATE NOT NULL,
  PRIMARY KEY(BLOG_ID),
  INDEX T_BLOG_FKIndex1(USER_ID)
);

CREATE TABLE T_BLOG_LABEL (
  BLOG_ID INTEGER UNSIGNED NOT NULL,
  LABEL_ID INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(BLOG_ID, LABEL_ID),
  INDEX T_BLOG_has_T_LABEL_FKIndex1(BLOG_ID),
  INDEX T_BLOG_has_T_LABEL_FKIndex2(LABEL_ID)
);

CREATE TABLE T_COMMENT (
  COMMENT_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  BLOG_ID INTEGER UNSIGNED NOT NULL,
  COMMENT_CONTENT VARCHAR(2000) NULL,
  COMMENT_USER_NAME VARCHAR(50) NULL,
  COMMENT_USER_EMAIL VARCHAR(200) NULL,
  COMMENT_DATE DATE NOT NULL,
  PRIMARY KEY(COMMENT_ID),
  INDEX T_COMMENT_FKIndex1(BLOG_ID)
);

CREATE TABLE T_LABEL (
  LABEL_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_ID INTEGER UNSIGNED NOT NULL,
  LABEL_NAME VARCHAR(50) NOT NULL,
  PRIMARY KEY(LABEL_ID),
  INDEX T_LABEL_FKIndex1(USER_ID)
);

CREATE TABLE T_USER (
  USER_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  LOGIN_NAME VARCHAR(50) NOT NULL,
  USER_NAME VARCHAR(50) NOT NULL,
  USER_EMAIL VARCHAR(200) NULL,
  USER_PASSWORD VARCHAR(2000) NOT NULL,
  USER_DATE DATE NOT NULL,
  USER_AUTHORITY VARCHAR(2000) NULL,
  PRIMARY KEY(USER_ID)
);


