CREATE TABLE T_BOOK (
  BOOK_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_ID INTEGER UNSIGNED NOT NULL,
  BOOK_TITLE VARCHAR(50) NOT NULL,
  BOOK_AUTHORS VARCHAR(5000) NULL,
  PUBLISH_DATE DATE NOT NULL,
  BOOK_INTRO VARCHAR(4000) NULL,
  BOOK_PRICE DOUBLE NULL,
  CREATED_DATE DATE NULL,
  PRIMARY KEY(BOOK_ID),
  INDEX T_BLOG_FKIndex1(USER_ID)
);

CREATE TABLE T_BOOK_LABEL (
  LABEL_ID INTEGER UNSIGNED NOT NULL,
  BOOK_ID INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(LABEL_ID, BOOK_ID),
  INDEX T_BLOG_has_T_LABEL_FKIndex2(LABEL_ID)
);

CREATE TABLE T_LABEL (
  LABEL_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  LABEL_NAME VARCHAR(50) NOT NULL,
  PRIMARY KEY(LABEL_ID)
);

CREATE TABLE T_REVIEW (
  REVIEW_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_ID INTEGER UNSIGNED NOT NULL,
  BOOK_ID INTEGER UNSIGNED NOT NULL,
  REVIEW_CONTENT VARCHAR(2000) NULL,
  REVIEW_DATE DATE NOT NULL,
  REVIEW_SCORE INTEGER UNSIGNED NULL,
  PRIMARY KEY(REVIEW_ID),
  INDEX T_REVIEW_FKIndex1(USER_ID)
);

CREATE TABLE T_USER (
  USER_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  LOGIN_NAME VARCHAR(50) NOT NULL,
  USER_NAME VARCHAR(50) NOT NULL,
  USER_EMAIL VARCHAR(200) NULL,
  USER_PASSWORD VARCHAR(2000) NOT NULL,
  USER_DATE DATE NOT NULL,
  USER_AUTHORITY VARCHAR(2000) NULL,
  PRIMARY KEY(USER_ID)
);


